### ISSUE TITLE
Failing junit-platform-maven-plugin (as extension)

### ISSUE THREAD

**Issue by khmarbaise** [sormuras/junit-platform-maven-plugin#29]
Currently I have a single module within my multi module build which contains the following configuration for the junit-platform-maven-plugin:

```xml
  <build>
    <plugins>
      <plugin>
        <groupId>de.sormuras.junit</groupId>
        <artifactId>junit-platform-maven-plugin</artifactId>
        <version>1.0.0-M5</version>
        <extensions>true</extensions> <!-- Necessary to execute it in 'test' phase. -->
        <dependencies>
          <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <version>1.4.0-M1</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
```

What I get during the execution is the following failure:
```
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ utils ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 4 source files to /Users/khmarbaise/.../utils/target/test-classes
[INFO] 
[INFO] --- junit-platform-maven-plugin:1.0.0-M5:launch (injected-launch) @ utils ---
[INFO] Launching JUnit Platform 1.3.2...
[WARNING] [WORKER] LegacyXmlReportGeneratingListener not found - JUnit Platform 1.4+ is required
Jan 23, 2019 7:46:12 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-jupiter' failed to execute tests
java.lang.NoSuchMethodError: org.junit.platform.commons.util.ReflectionUtils.tryToLoadClass(Ljava/lang/String;)Lorg/junit/platform/commons/function/Try;
	at org.junit.jupiter.engine.support.OpenTest4JAndJUnit4AwareThrowableCollector.createAbortedExecutionPredicate(OpenTest4JAndJUnit4AwareThrowableCollector.java:40)
	at org.junit.jupiter.engine.support.OpenTest4JAndJUnit4AwareThrowableCollector.<clinit>(OpenTest4JAndJUnit4AwareThrowableCollector.java:30)
	at org.junit.jupiter.engine.support.JupiterThrowableCollectorFactory.createThrowableCollector(JupiterThrowableCollectorFactory.java:34)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:68)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at de.sormuras.junit.platform.isolator.worker.Worker.call(Worker.java:90)
	at de.sormuras.junit.platform.isolator.worker.Worker.call(Worker.java:28)
	at de.sormuras.junit.platform.isolator.Isolator.evaluate(Isolator.java:84)
	at de.sormuras.junit.platform.maven.plugin.JUnitPlatformMojo.lambda$executeDirect$7(JUnitPlatformMojo.java:434)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[INFO] [WORKER] Successfully executed 0 test(s) in 16 ms
[INFO] [WORKER] Find test run details at file:///Users/khmarbaise/.../utils/target/junit-platform/junit-platform-summary.txt
```
I have also added the `junit-platform-launcher` (with version 1.4.0-M1` to my dependencies).

Maybe I have misunderstood something ?

**Comment by sormuras** [comment]
You should not (need to) add this to the plugin:

        <dependencies>
          <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <version>1.4.0-M1</version>
          </dependency>
        </dependencies>

A matching (to your project dependencies) version of the JUnit Platform Launcher will be added.

Reading the log it states: `Launching JUnit Platform 1.3.2...` ...so somehow the plugin thinks you want to run on JUnit Platform `1.3.2`. You may override that auto-platform-version-logic via this configuration:

        <configuration>
          <versions>
            <junit.platform.version>1.4.0-M1</junit.platform.version>
          </versions>
        </configuration>

May you post your `pom.xml` file here?

**Comment by sormuras** [comment]
`ReflectionUtils.tryToLoadClass` was introduced in `1.4.0-SNAPSHOT` ... so, it seems like there's still a `junit-platform-commons` in version `1.3.2` or lower in your dependencies.

**Comment by khmarbaise** [comment]
No I'm using `junit-jupiter[-api]:5.4.0-M1`..

```xml
  <build>
    <plugins>
      <plugin>
        <groupId>de.sormuras.junit</groupId>
        <artifactId>junit-platform-maven-plugin</artifactId>
        <version>1.0.0-M5</version>
        <extensions>true</extensions> <!-- Necessary to execute it in 'test' phase. -->
        <configuration>
          <versions>
            <junit.platform.version>1.4.0-M1</junit.platform.version>
          </versions>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apiguardian</groupId>
      <artifactId>apiguardian-api</artifactId>
    </dependency>
  </dependencies>
```
All the dependencies are handled by dependencyManagement with version `5.4.0-M1` ...
So tried to get dependency tree:
```
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ utils ---
[INFO] de.ibm.leidad:utils:jar:0.4.0-SNAPSHOT
[INFO] +- org.junit.jupiter:junit-jupiter-engine:jar:5.4.0-M1:test
[INFO] |  \- org.junit.platform:junit-platform-engine:jar:1.3.2:test
[INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.4.0-M1:test
[INFO] |  +- org.opentest4j:opentest4j:jar:1.1.1:test
[INFO] |  \- org.junit.platform:junit-platform-commons:jar:1.3.2:test
[INFO] +- org.assertj:assertj-core:jar:3.10.0:test
[INFO] \- org.apiguardian:apiguardian-api:jar:1.0.0:compile
```
which from my point of view shows the issue: Seeing the platform-engin:jar:1.3.2 ? Or is it not? I can created a separate test project for this?

**Comment by sormuras** [comment]
```
[INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.4.0-M1:test
[INFO] |  +- org.opentest4j:opentest4j:jar:1.1.1:test
[INFO] |  \- org.junit.platform:junit-platform-commons:jar:1.3.2:test
```

This _really_ looks odd.

**Comment by sormuras** [comment]
According to https://search.maven.org/artifact/org.junit.jupiter/junit-jupiter-api/5.4.0-M1/jar -- it correctly depends on `org.junit.platform:junit-platform-commons:1.4.0-M1`.

> All the dependencies are handled by dependencyManagement with version `5.4.0-M1`.

Sure?

**Comment by khmarbaise** [comment]
Let me check this...

**Comment by sormuras** [comment]
Lets switch to Slack, if you want.

**Comment by khmarbaise** [comment]
ASF Slack?

**Comment by sormuras** [comment]
Aye.

**Comment by khmarbaise** [comment]
The issue was the spring-boot-dependency bom which contains an older version of junit-jupiter (5.3.2). The simple solution was to add the junit-bom before the spring-boot-dependency bom in my dependencyManagement.

**Comment by sbrannen** [comment]
@khmarbaise, you may also find the following helpful.

https://stackoverflow.com/a/54605523/388980
