### ISSUE TITLE
MalformedInputException on Windows on JDK 18 and 19-ea

### ISSUE THREAD

**Issue by dbwiddis** [sormuras/junit-platform-maven-plugin#95]
Unfortunately I haven't been able to generate a minimum reproducible example, as I can't reproduce it locally, but I'm failing my Windows JDK 18 and 19-ea builds (repeatably) with this error:
> MalformedInputException: Input length = 1

It appears near the end of my test run when I'm outputting a large # of characters to the log buffer.  I've tried slowing down my own output, but that doesn't seem to help as it's still redirected to a file which is later read from the filesystem by junit-platform-maven-plugin.

Here's a sample run causing the error:  https://github.com/oshi/oshi/runs/5841059313?check_suite_focus=true

This StackOverflow question suggests a possible explanation/solution:
https://stackoverflow.com/questions/30609062/java-nio-charset-malformedinputexception-input-length-1

My guess is the new UTF-8 default encoding in JDK 18 may be running afoul of the default encoding on the GitHub Actions servers, likely UTF-16LE(?).

The fix would be applied here:
https://github.com/sormuras/junit-platform-maven-plugin/blob/0475e00414200cffe072a5f46226268558f29a04/src/main/java/de/sormuras/junit/platform/maven/plugin/JavaExecutor.java#L141-L142

The answers on this question also have some interesting ideas to work around the issue: https://stackoverflow.com/questions/26268132/all-inclusive-charset-to-avoid-java-nio-charset-malformedinputexception-input?msclkid=18812937b54211ec91894e2d16ce221d

I'll keep trying to isolate a smaller reproducible case but figured this is probably enough info to try to fix it.

Full stack trace:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:47)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:156)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:72)
Caused by: java.lang.AssertionError: Unexpected exception caught!
	at de.sormuras.junit.platform.maven.plugin.JUnitPlatformMojo.execute(JUnitPlatformMojo.java:444)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 4 more
Caused by: java.io.UncheckedIOException: java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.file.FileChannelLinesSpliterator.readLine(FileChannelLinesSpliterator.java:192)
	at java.base/java.nio.file.FileChannelLinesSpliterator.forEachRemaining(FileChannelLinesSpliterator.java:132)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at de.sormuras.junit.platform.maven.plugin.JavaExecutor.evaluate(JavaExecutor.java:144)
	at de.sormuras.junit.platform.maven.plugin.JUnitPlatformMojo.executeJava(JUnitPlatformMojo.java:475)
	at de.sormuras.junit.platform.maven.plugin.JUnitPlatformMojo.execute(JUnitPlatformMojo.java:453)
	at de.sormuras.junit.platform.maven.plugin.JUnitPlatformMojo.execute(JUnitPlatformMojo.java:434)
	... 25 more
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
	at java.base/java.nio.file.FileChannelLinesSpliterator.readLine(FileChannelLinesSpliterator.java:190)
	... 31 more
```

**Comment by sormuras** [comment]
An interesting case, thanks for reporting it, Daniel.

> My guess is the new UTF-8 default encoding in JDK 18 may be running afoul of the default encoding on the GitHub Actions servers, likely UTF-16LE(?).

Possible. Yet `Files.lines(Path)` always uses `UTF-8` since Java 8, so it should fail on older Java versions as well...

**Comment by dbwiddis** [comment]
> Possible. Yet `Files.lines(Path)` always uses `UTF-8` since Java 8, so it should fail on older Java versions as well...

Yeah, I had that thought as well.  My next idea is something with `System.lineSeparator()`.  The output string causing the issues has a lot of single `\n` characters ending a line.  But I can't see where that would make a difference either.  I'll keep poking at it.

**Comment by dbwiddis** [comment]
The plot thickens.  The exception happens in new code from this commit:
https://github.com/openjdk/jdk/commit/433096a45ea847e2e2ae8cd5a100971939f6a11f

The offending method has an interesting comment at the start:
```java
    int implRead(char[] cbuf, int off, int end) throws IOException {
        // In order to handle surrogate pairs, this method requires that
        // the invoker attempt to read at least two characters.  Saving the
        // extra character, if any, at a higher level is easier than trying
        // to deal with it here.
```

So I'm wondering if this is a JDK bug...

**Comment by dbwiddis** [comment]
(Looks like that code is in JDK 17 which works, but perhaps there's something with UTF-8 changing the logic path.)

**Comment by rmannibucau** [comment]
Tried on linux with zulu 18 and didn't get any issue so either it is a windows related issue or env one. Anyone able to reproduce locally?

**Comment by dbwiddis** [comment]
> Tried on linux with zulu 18 and didn't get any issue so either it is a windows related issue or env one. 

My Linux and macOS 18 and 19ea builds had no problem.  This only occurred on Windows.

I couldn't reproduce it when I tried in my git bash shell (MinGW), but will be trying tomorrow using the maven wrapper on command line.  So far the repro case seems to be "large amount of `\n`-delimited ASCII text on Windows`.

**Comment by rmannibucau** [comment]
Anyway, since we don't know what is output we could just use bytes and split on`\n[\r]` maybe? outputstream to logger often do that.
That said it would be better to stream the output instead of waiting for the execution probably so maybe something to rework in file mode?

**Comment by dbwiddis** [comment]
> Anyway, since we don't know what is output we could just use bytes and split on`\n[\r]` maybe?

In UTF-16 that will leave a stray null byte before or after (depending on LE or BE).  And the `\r\n` may have a null byte between them.  

I do think using bytes and using some sequence of try/catch to detect encoding might be useful.

**Comment by sormuras** [comment]
I was able to reproduce the `MalformedInputException` on my Windows machine:

```text
Microsoft Windows [Version 10.0.22000.556]
```

_gathering more system information... with oshi_

**Comment by sormuras** [comment]
Seems like `console-launcher.XXX.log` file are not always encoded in UTF-8. 🤔

![image](https://user-images.githubusercontent.com/2319838/161940010-971aab29-777e-4981-9f3b-007d50b79aa6.png)

Setting codepage to UTF (via `chcp 65001`) has no effect.

**Comment by rmannibucau** [comment]
@sormuras even with `-Dfile.encoding=UTF-8` on maven JVM?

**Comment by sormuras** [comment]
> @sormuras even with -Dfile.encoding=UTF-8 on maven JVM?

Yes. Tried:
- `mvnw test -B -e -D"license.skip=true" -Dfile.encoding=UTF-8`
- `mvnw test -B -e -D"license.skip=true" -D"file.encoding=UTF-8"`

OSHI's `pom.xml` also set UTF-8 everywhere:

https://github.com/oshi/oshi/blob/146bf21d1fbebae546e3f2dab6299a4cdc2b4174/pom.xml#L89-L91

**Comment by rmannibucau** [comment]
maybe we should just read the bom and check it, it is about pre-reading a buffer of 4 bytes so does not sounds terrible, something like https://github.com/albfernandez/juniversalchardet/blob/main/src/main/java/org/mozilla/universalchardet/UniversalDetector.java#L238 ?

**Comment by sormuras** [comment]
The JUnit Platform Console Launcher uses this code to write messages to standard streams:
```java
public static void main(String... args) {
  int exitCode = execute(System.out, System.err, args).getExitCode();
  System.exit(exitCode);
}

@API(status = INTERNAL, since = "1.0")
public static ConsoleLauncherExecutionResult execute(PrintStream out, PrintStream err, String... args) {
  return execute(new PrintWriter(out), new PrintWriter(err), args);
}
```
https://github.com/junit-team/junit5/blob/9a35e7fb701b752b2875c3437c45452212fd0b09/junit-platform-console/src/main/java/org/junit/platform/console/ConsoleLauncher.java#L36-L44

The encoding of standard output and error streams were not touched by [JEP 400](https://openjdk.java.net/jeps/400). Thus, JUnit will use platform native encoding (here `windows-1252`) for `System.out` and `System.err`. All characters streamed by JUnit are redirected using the ProcessBuilder API by the `JAVA` executor:
https://github.com/sormuras/junit-platform-maven-plugin/blob/0475e00414200cffe072a5f46226268558f29a04/src/main/java/de/sormuras/junit/platform/maven/plugin/JavaExecutor.java#L62-L63
Reading in lines via `Files.lines(Path)` from `console-launcher.out.log` and `console-launcher.err.log` assumes they are UTF-8 encoded.

What I don't fully understand, why does work with Java 17? `Files.lines(Path)` did always use UTF-8, no matter what the default encoding is.

**Comment by dbwiddis** [comment]
> Yes. Tried:
> 
> * `mvnw test -B -e -D"license.skip=true" -Dfile.encoding=UTF-8`
> * `mvnw test -B -e -D"license.skip=true" -D"file.encoding=UTF-8"`

Does that carry through to the console launcher ? Would adding `-D"file.encoding=UTF-8"` in `<javaOptions>` help?

**Comment by sormuras** [comment]
Found an easy reproducer as well.

![image](https://user-images.githubusercontent.com/2319838/161995406-d6f5b85e-4e85-4dca-be60-bdf6c530bf70.png)

Replacing `test` with `täßt` suffices to make the plugin choke on non-UTF-8 systems using Java 18+ ... with `<executor>JAVA</executor>` that is.

**Comment by sormuras** [comment]
_Fix (as proposed in [JEP 400](https://openjdk.java.net/jeps/400)) in progres..._

> Where application code can be changed, then we recommend it is changed to pass a charset argument to constructors. If an application has no particular preference among charsets, and is satisfied with the traditional environment-driven selection for the default charset, then the following code can be used on all Java releases to obtain the charset determined from the environment:

```java
String encoding = System.getProperty("native.encoding");  // Populated on Java 18 and later
Charset cs = (encoding != null) ? Charset.forName(encoding) : Charset.defaultCharset();
var reader = new FileReader("file.txt", cs);
```

**Comment by sormuras** [comment]
For future-me: https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/io/PrintStream.html#charset()

>  Returns the charset used in this PrintStream instance.
>
> 
 Since:
>  **18**

**Comment by dbwiddis** [comment]
As I was updating my GHA's to the new JDK I happened on a comment that my windows tests are still disabled due to this.  Any chance of it making it into a release anytime soon?

**Comment by dbwiddis** [comment]
> The fix already shipped, right?

Yep. See #115.   
1. Found the offending character that caused this issue on windows
2. It's a little more complicated now
